"""translation on private messages

Revision ID: cb74289c3cd0
Revises: 5e3e16d6f285
Create Date: 2019-04-19 13:30:41.378478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb74289c3cd0'
down_revision = '5e3e16d6f285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'language')
    # ### end Alembic commands ###
